"""Add email to participante

Revision ID: 7c7f3258505e
Revises: 531c96026156
Create Date: 2023-09-03 18:18:58.781024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c7f3258505e'
down_revision = '531c96026156'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correo', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participante', schema=None) as batch_op:
        batch_op.drop_column('correo')

    # ### end Alembic commands ###
